import javax.swing.*;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * add.java
 *
 * Created on Apr 7, 2017, 11:53:03 AM
 */

/**
 *
 * @author DAV
 */
public class add extends javax.swing.JFrame {

    /** Creates new form add */
    public add() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(755, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel1.setText("Employee Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 120, 24);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 81, 24);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 77, 24);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 53, 24);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 210, 47, 24);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jLabel6.setText("Contact");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 260, 55, 24);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jLabel7.setText("Date Of join");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 320, 92, 24);

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jLabel8.setText("Designation");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 370, 90, 24);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 0, 14));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 20, 210, 32);

        jTextField2.setFont(new java.awt.Font("Segoe Print", 0, 14));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 60, 210, 32);

        jTextField3.setFont(new java.awt.Font("Segoe Print", 0, 14));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 110, 210, 32);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setText("Male");
        jRadioButton1.setOpaque(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(240, 160, 61, 33);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jRadioButton2.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setText("Female");
        jRadioButton2.setOpaque(false);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(320, 160, 90, 33);

        jTextField4.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jTextField4.setText(" ");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 210, 210, 32);

        jTextField5.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 260, 210, 32);

        jTextField6.setFont(new java.awt.Font("Segoe Print", 0, 14));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(240, 310, 220, 32);

        jLabel9.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jLabel9.setText("Salary");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 440, 49, 24);

        jTextField7.setFont(new java.awt.Font("Segoe Print", 0, 14));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(250, 440, 210, 32);

        jButton1.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton1.setForeground(new java.awt.Color(51, 255, 51));
        jButton1.setText("Add Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 500, 210, 50);

        jButton2.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ree1.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 500, 180, 50);

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jRadioButton3.setText("Head Manager");
        jRadioButton3.setOpaque(false);
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(160, 360, 133, 33);

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jRadioButton4.setText("Branch Manager");
        jRadioButton4.setOpaque(false);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(290, 360, 151, 33);

        jRadioButton5.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jRadioButton5.setText("Peo");
        jRadioButton5.setOpaque(false);
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(450, 360, 60, 33);

        jRadioButton6.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jRadioButton6.setText("Gaurd");
        jRadioButton6.setOpaque(false);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(510, 360, 73, 33);

        jRadioButton7.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jRadioButton7.setText("Cashier");
        jRadioButton7.setOpaque(false);
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(590, 360, 83, 33);

        jButton3.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACK.PNG"))); // NOI18N
        jButton3.setText("Back to menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 500, 220, 50);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nki.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-40, -40, 790, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
            c.createStatement();
            PreparedStatement p;
            String a="",b="";
            String s="insert into addition(id,fname,lname,gender,email,contact,doj,designation,salary) values(?,?,?,?,?,?,?,?,?)";
            if(jRadioButton1.isSelected()){
                a="Male";
            }
            if(jRadioButton2.isSelected()){
                a="Female";
            }
            if(jRadioButton3.isSelected()){
                b="Head Manager";
            }
            if(jRadioButton4.isSelected()){
                b="Branch Manager";
            }
            if(jRadioButton5.isSelected()){
                b="Peo";
            }
            if(jRadioButton6.isSelected()){
                b="Guard";
            }
            if(jRadioButton7.isSelected()){
                b="Cashier";
            }
            p=c.prepareStatement(s);
            p.setString(1,jTextField1.getText());
            p.setString(2,jTextField2.getText());
            p.setString(3,jTextField3.getText());
            p.setString(4,a);
            p.setString(5,jTextField4.getText());
            p.setString(6,jTextField5.getText());
            p.setString(7,jTextField6.getText());
            p.setString(8,b);
            p.setString(9,jTextField7.getText());
            p.execute();
            JOptionPane.showMessageDialog(null,"Record Added");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",1);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new welcome().setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
