import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * deductions.java
 *
 * Created on Apr 11, 2017, 4:14:17 PM
 */

/**
 *
 * @author hp
 */
public class deductions extends javax.swing.JFrame {

    /** Creates new form deductions */
    public deductions() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(948, 830));
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ree1.PNG"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 610, 180, 40);

        jButton1.setFont(new java.awt.Font("Old English Text MT", 0, 18));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SE.PNG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 10, 150, 40);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(400, 20, 100, 32);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 18));
        jLabel1.setText("Emplyee ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 130, 20);

        jButton5.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACK.PNG"))); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(390, 610, 180, 40);

        jButton4.setFont(new java.awt.Font("Old English Text MT", 0, 22)); // NOI18N
        jButton4.setText("DEDUCT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 610, 160, 40);

        jLabel12.setFont(new java.awt.Font("Old English Text MT", 0, 18));
        jLabel12.setText("Other Taxes");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 550, 100, 19);

        jLabel11.setFont(new java.awt.Font("Old English Text MT", 0, 18));
        jLabel11.setText("1% Govt Tax");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 500, 160, 19);

        jTextField10.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField10);
        jTextField10.setBounds(450, 550, 140, 32);

        jTextField9.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(440, 490, 150, 32);

        jTextField12.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField12);
        jTextField12.setBounds(710, 520, 150, 32);

        jLabel15.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel15.setText("Net Salary");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(720, 480, 110, 19);

        jTextField11.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField11);
        jTextField11.setBounds(700, 380, 150, 32);

        jLabel14.setFont(new java.awt.Font("Old English Text MT", 0, 18));
        jLabel14.setText("Total Deduction");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(710, 340, 170, 19);

        jButton2.setFont(new java.awt.Font("Old English Text MT", 0, 22)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(710, 430, 150, 31);

        jTextField8.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(440, 430, 150, 32);

        jLabel10.setFont(new java.awt.Font("Old English Text MT", 0, 18));
        jLabel10.setText("Leaves");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 440, 100, 19);

        jTextField7.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(440, 370, 150, 32);

        jLabel9.setFont(new java.awt.Font("Old English Text MT", 0, 18));
        jLabel9.setText("Advance Pay");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 380, 110, 19);

        jTextField6.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(440, 330, 150, 32);

        jLabel8.setFont(new java.awt.Font("Old English Text MT", 0, 18));
        jLabel8.setText("Gross Salary");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 330, 110, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "lastname", "gender", "email", "contact no", "doj", "degination", "salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 50, 800, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nki.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, -190, 910, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

           DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
        try{
            ResultSet rs;
            PreparedStatement pst;
            Connection con=null;
            Class.forName("java.sql.DriverManager");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
            Statement s=con.createStatement();
            String a=jTextField1.getText();
            String sql="Select*from addition where id='"+a+"';";
            rs=s.executeQuery(sql);
            pst=con.prepareStatement(sql);
            while(rs.next()) {
                String s1=rs.getString("id");
                String s2=rs.getString("fname");
                String s3=rs.getString("lname");
                String s4=rs.getString("gender");
                String s5=rs.getString("email");
                String s6=rs.getString("contact");
                String s7=rs.getString("doj");
                String s8=rs.getString("designation");
                String s9=rs.getString("salary");
                m.addRow(new Object[]{s1,s2,s3,s4,s5,s6,s7,s8,s9});

            }
            rs.close();
            s.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",1);
        }




    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Double a, b,c,d,e,f;
        a=Double.parseDouble(jTextField6.getText());
        b=Double.parseDouble(jTextField6.getText());
        c=Double.parseDouble(jTextField6.getText());
        d=Double.parseDouble(jTextField6.getText());
        e=Double.parseDouble(jTextField6.getText());
       f= (a+b)-(c+d+e);
       jTextField11.setText(""+f);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       Double a, b,c,d;
        a=Double.parseDouble(jTextField6.getText());
        b=Double.parseDouble(jTextField7.getText());
        c=Double.parseDouble(jTextField11.getText());
        d=(a+b)-c;
        jTextField12.setText(""+d);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
         new welcome().setVisible(true);



    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText("");
         jTextField6.setText("");
         jTextField7.setText("");
         jTextField8.setText("");
         jTextField9.setText("");
         jTextField10.setText("");
         jTextField11.setText("");
         jTextField12.setText("");


        jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Firstname","lastname","gender","email","contact no","doj","designation","salary"}));

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deductions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
