import javax.swing.*;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * payroll.java
 *
 * Created on Jan 18, 2017, 8:08:00 PM
 */

/**
 *
 * @author ultimate
 */
public class payroll extends javax.swing.JFrame {

    /** Creates new form payroll */
    public payroll() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setMinimumSize(new java.awt.Dimension(898, 549));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Old English Text MT", 1, 36));
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("WEL-COME TO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 60, 340, 60);

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 3, 34));
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText(" PAYROLL MANAGEMENT  SYSTEM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 160, 670, 60);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 26));
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Enter Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 250, 230, 44);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 26));
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 360, 160, 30);

        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 18));
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/for2.PNG"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 450, 140, 50);

        jButton2.setFont(new java.awt.Font("Segoe Print", 0, 18));
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/l2.PNG"))); // NOI18N
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(570, 450, 150, 50);

        jPasswordField1.setFont(new java.awt.Font("Monotype Corsiva", 3, 14));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 0));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(520, 360, 180, 40);

        jTextField1.setFont(new java.awt.Font("Viner Hand ITC", 3, 16));
        jTextField1.setForeground(new java.awt.Color(255, 255, 51));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(520, 260, 180, 40);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nki.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 900));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 900));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // String sql="Select * from login";
         this.setVisible(false);
     try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection c= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");





            Statement s=c.createStatement();
           String sql="Select * from login";
            ResultSet rs = s.executeQuery(sql);
            String user=jTextField1.getText();
            String pwd= new String(jPasswordField1.getPassword());
            while(rs.next()){


            String uname=rs.getString("UserName");

          String password=rs.getString("Password");
           if ((user.equals(uname)) && (pwd.equals(password)))
           {
                //JOptionPane.showMessageDialog(null,"login sucessful");
                 new welcome().show();
          break;
           }

        else
            JOptionPane.showMessageDialog(this, "Incorrect Username or Password!");

        }
     }
            catch (Exception e)
            {
                      JOptionPane.showMessageDialog(this, e.getMessage());
        }





       




    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
new forget().show();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
