import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * searchnew.java
 *
 * Created on Apr 28, 2017, 12:17:49 PM
 */

/**
 *
 * @author DAV
 */
public class searchnew extends javax.swing.JFrame {

    /** Creates new form searchnew */
    public searchnew() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(892, 517));
        getContentPane().setLayout(null);

        jButton4.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ree1.PNG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(70, 420, 180, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SE.PNG"))); // NOI18N
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 40, 170, 50);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(360, 60, 140, 32);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 24));
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 60, 40, 40);

        jButton3.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACK.PNG"))); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 420, 190, 50);

        jButton2.setFont(new java.awt.Font("Old English Text MT", 0, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/S2.PNG"))); // NOI18N
        jButton2.setText("ALL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 420, 240, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "lastname", "gender", "email", "contact no", "doj", "degination", "salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 150, 760, 260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nki.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 810, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
        try{
            ResultSet rs;
            PreparedStatement pst;
            Connection con=null;
            Class.forName("java.sql.DriverManager");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
            Statement s=con.createStatement();
            String a=jTextField1.getText();
            String sql="Select*from addition where id='"+a+"';";
            rs=s.executeQuery(sql);
            pst=con.prepareStatement(sql);
            while(rs.next()) {
                String s1=rs.getString("id");
                String s2=rs.getString("fname");
                String s3=rs.getString("lname");
                String s4=rs.getString("gender");
                String s5=rs.getString("email");
                String s6=rs.getString("contact");
                String s7=rs.getString("doj");
                String s8=rs.getString("designation");
                String s9=rs.getString("salary");
                m.addRow(new Object[]{s1,s2,s3,s4,s5,s6,s7,s8,s9});

            }
            rs.close();
            s.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",1);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
        try{
ResultSet rs;
    PreparedStatement pst;
    Connection con=null;
            Class.forName("java.sql.DriverManager");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
            Statement s=con.createStatement();
            String sql="Select*from addition";
            rs=s.executeQuery(sql);
            pst=con.prepareStatement(sql);
            while(rs.next())
            {
             String s1=rs.getString("id");
                String s2=rs.getString("fname");
                String s3=rs.getString("lname");
                String s4=rs.getString("gender");
                String s5=rs.getString("email");
                String s6=rs.getString("contact");
                String s7=rs.getString("doj");
                String s8=rs.getString("designation");
                String s9=rs.getString("salary");
                m.addRow(new Object[]{s1,s2,s3,s4,s5,s6,s7,s8,s9});

            }



              rs.close();
                   s.close();
                     con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
         new welcome().setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
 jTextField1.setText("");

        jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Firstname","lastname","gender","email","contact no","doj","designation","salary"}));

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchnew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
