import javax.swing.*;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * update.java
 *
 * Created on Apr 7, 2017, 12:22:15 PM
 */

/**
 *
 * @author DAV
 */
public class update extends javax.swing.JFrame {

    /** Creates new form update */
    public update() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField8 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField8.setText("jTextField8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(816, 662));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel3.setText("First Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 90, 82, 26);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 130, 80, 26);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 180, 50, 26);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 230, 44, 26);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel7.setText("Contact No:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 270, 85, 26);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel8.setText("Date Of Join:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 310, 94, 26);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel9.setText("Desigation:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 360, 90, 26);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel10.setText("Salary");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 410, 44, 26);

        jTextField2.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(390, 90, 130, 32);

        jTextField3.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(390, 130, 130, 32);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jRadioButton1.setText("Male");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(400, 170, 57, 35);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(480, 170, 73, 35);

        jTextField4.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(400, 220, 130, 32);

        jTextField5.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(400, 270, 130, 32);

        jTextField6.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(400, 310, 130, 32);

        jTextField7.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(400, 410, 130, 32);

        jButton2.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ree1.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 471, 170, 50);

        jButton3.setFont(new java.awt.Font("Old English Text MT", 0, 22)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UP1.PNG"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 470, 180, 50);

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jRadioButton7.setText("Cashier");
        jRadioButton7.setOpaque(false);
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(660, 360, 77, 35);

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jRadioButton6.setText("Gaurd");
        jRadioButton6.setOpaque(false);
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(590, 360, 69, 35);

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jRadioButton5.setText("Peo");
        jRadioButton5.setOpaque(false);
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(530, 360, 51, 35);

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jRadioButton4.setText("Branch Manager");
        jRadioButton4.setOpaque(false);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(380, 360, 150, 35);

        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jRadioButton3.setText("Head Manager");
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(250, 360, 130, 35);

        jButton1.setFont(new java.awt.Font("Old English Text MT", 0, 22));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACK.PNG"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 471, 170, 50);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(390, 50, 130, 32);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 14));
        jLabel1.setText("Employee Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 50, 110, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nki.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 790, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String a="",b="";
        ResultSet rs;
        PreparedStatement p;
        Connection con=null;
        int n=JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Update ?");
        if(jRadioButton1.isSelected()){
                 a="Male";
            }
            if(jRadioButton2.isSelected()){
                 a="Female";
            }
            if(jRadioButton3.isSelected()){
                 b="Head Manager";
            }
            if(jRadioButton4.isSelected()){
                 b="Branch Manager";
            }
            if(jRadioButton5.isSelected()){
                 b="Peo";
            }
            if(jRadioButton6.isSelected()){
                 b="Guard";
            }
            if(jRadioButton7.isSelected()){
                 b="Cashier";
            }
        if(n==JOptionPane.YES_OPTION){
            try{
                Class.forName("java.sql.DriverManager");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
                Statement s= con.createStatement();
                String sql="update addition set fname='"+jTextField2.getText()+"',lname='"+jTextField3.getText()+"',gender='"+a+"',email='"+jTextField4.getText()+"',contact='"+jTextField5.getText()+"',doj='"+jTextField6.getText()+"',designation="+b+",salary="+jTextField7.getText()+" where id="+jTextField1.getText()+";" ;
                s.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Record Updated Sucessfully");
            }
            catch(Exception e){
                  JOptionPane.showMessageDialog(null,e.getMessage(),"Error",1);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
         new welcome().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
