import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Update_Salary.java
 *
 * Created on Apr 28, 2017, 5:47:09 PM
 */

/**
 *
 * @author hp
 */
public class Update_Salary extends javax.swing.JFrame {

    /** Creates new form Update_Salary */
    public Update_Salary() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 700));
        getContentPane().setLayout(null);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ree1.PNG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(490, 560, 160, 40);

        jButton2.setFont(new java.awt.Font("Old English Text MT", 0, 14));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACK.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 560, 110, 40);

        jButton3.setFont(new java.awt.Font("Segoe Script", 1, 18));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UP1.PNG"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 560, 170, 40);

        jTextField7.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(410, 360, 180, 32);

        jTextField8.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(300, 460, 150, 30);

        jTextField2.setFont(new java.awt.Font("Segoe Print", 1, 14));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(580, 490, 110, 32);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jRadioButton2.setText("amount");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(340, 400, 90, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jRadioButton1.setText("percent");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(160, 400, 90, 20);

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jLabel8.setText("New Salary");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 430, 110, 24);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jLabel7.setText("Current Salary:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 360, 120, 24);

        jButton1.setFont(new java.awt.Font("Segoe Script", 1, 14));
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SE.PNG"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 30, 160, 50);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 50, 100, 20);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Emplyee ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 50, 120, 23);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 2, 2);

        jTable1.setFont(new java.awt.Font("Segoe Script", 1, 12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "lastname", "gender", "email", "contact no", "doj", "degination", "salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 700, 250);

        jButton5.setFont(new java.awt.Font("Yahoo!©", 0, 12));
        jButton5.setText("calculate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(70, 460, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nki.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, 10, 740, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        PreparedStatement p;
        Connection con=null;
        int n=JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Update ?");
        
            if(n==JOptionPane.YES_OPTION){

                try{
                    Class.forName("java.sql.DriverManager");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
                    Statement s= con.createStatement();
                    String sql="update addition set salary='"+jTextField2.getText()+"' where id='"+jTextField1.getText()+"' ;" ;
                    s.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Record Updated Sucessfully");
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Error",1);
                }
            }





        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
        try{
            ResultSet rs;
            PreparedStatement pst;
            Connection con=null;
            Class.forName("java.sql.DriverManager");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
            Statement s=con.createStatement();
            String a=jTextField1.getText();
            String sql="Select*from addition where id='"+a+"';";
            rs=s.executeQuery(sql);
            pst=con.prepareStatement(sql);
            while(rs.next()) {
                String s1=rs.getString("id");
                String s2=rs.getString("fname");
                String s3=rs.getString("lname");
                String s4=rs.getString("gender");
                String s5=rs.getString("email");
                String s6=rs.getString("contact");
                String s7=rs.getString("doj");
                String s8=rs.getString("designation");
                String s9=rs.getString("salary");
                m.addRow(new Object[]{s1,s2,s3,s4,s5,s6,s7,s8,s9});

            }
            rs.close();
            s.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",1);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new welcome().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       jTextField1.setText("");
       jTextField2.setText("");
       jTextField7.setText("");
       jTextField8.setText("");
       jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Firstname","lastname","gender","email","contact no","doj","designation","salary"}));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        double a=0;
        double b=Double.parseDouble(jTextField8.getText());
        double c=Double.parseDouble(jTextField7.getText());
        if(jRadioButton1.isSelected()){
            a=(c*(b/100))+c;
            jTextField2.setText(""+a);
        }
        if(jRadioButton2.isSelected()){

            a=b+c;
            jTextField2.setText(""+a);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
